language: node_js
node_js: 'stable'

cache:
  directories:
    - $HOME/.npm

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - npm run migrate

after_success:
  - coveralls < coverage/lcov.info
